### PR TITLE
agent: Remove dev from pciDeviceMap when device is unplugged

### LINKED ISSUE #729: Remove dev from pciDeviceMap when device is unplugged
**Which feature do you think can be improved?**

According to https://github.com/kata-containers/runtime/pull/2008, the agent needs to remove the dev from `pciDeviceMap` when device is unplugged. Otherwise `getDeviceName` will not block until ready when a dev with reused index is plugged.

**How can it be improved?**
Delete `uEv.DevPath` from pciDeviceMap when recieving `remove` uevent.

### PR DESCRIPTION
**Pull request by darfux**
Delete `uEv.DevPath` from pciDeviceMap when recieving `remove` uevent.

Fixes #729
Signed-off-by: Li Yuxuan <liyuxuan04@baidu.com>

### CODE REVIEW

**Comment by devimc** [comment]
thanks @darfux 

/test

**Comment by darfux** [comment]
Added `span.finish()` before continue the loop. Sorry for missing it 😥

**Comment by devimc** [comment]
hey @darfux don't worry :smile:

/test

**Comment by darfux** [comment]
Thanks @devimc , could you plz restart the failed cases? `ubuntu-18-04-initrd` is failed on rootfs.sh and I'm trying to find out why `centos-8-q-35` is failed

**Comment by grahamwhaley** [comment]
@darfux - I've nudged the two failed CIs for rebuilds.

**Comment by darfux** [comment]
Thanks @grahamwhaley ! `ubuntu-18-04-initrd` is ok now. And `centos-8-q-35` was failed on docker build stage with *Error: Failed to download metadata for repo 'AppStream'*. So could you please restart it again?😂

**Comment by grahamwhaley** [comment]
done. kicked rebuild.

**Comment by devimc** [comment]
one more review here please

**Comment by devimc** [comment]
ping @jodh-intel @amshinde @grahamwhaley

**Comment by amshinde** [comment]
same comment as @grahamwhaley. Would like @jodh-intel to take a look at the span handling before this is merged.

**Comment by darfux** [comment]
Thanks for reviewing! Hi @jodh-intel could you plz take a look at the span handling? 😁

**Comment by jodh-intel** [comment]
Merging blocked due to the dnm label still - can this be removed now?

**Comment by darfux** [comment]
Thanks @jodh-intel. I've applied your suggestion
/cc @amshinde  for the DNM label :)

**Comment by jodh-intel** [comment]
Thanks @darfux.

**Comment by grahamwhaley** [comment]
/test
and DNM dropped.

**Comment by darfux** [comment]
Thanks @grahamwhaley . The `ubuntu-18-04-initrd` case was failed in Spec Setup which is similar with http://jenkins.katacontainers.io/job/kata-containers-agent-ubuntu-18-04-PR-initrd/582. Could you plz restart it 😆

**Comment by grahamwhaley** [comment]
np, scheduled....

**Pull request merged**
