### PR TITLE
Revert vendor: Update libcontainer vendoring

### PR DESCRIPTION
**Pull request by teawater**
According discussion with @lifupan in https://github.com/kata-containers/runtime/pull/1414
Try to revert vendor: Update libcontainer vendoring to fix the issue.

### CODE REVIEW

**Comment by teawater** [comment]
I still cannot make sure that these patches can fix all the issue because the issue is around a random fail.
So I will do tests a lot of times to make sure the PR fix the issue on each test environment.

**Comment by sboeuf** [comment]
@teawater @jodh-intel I'd like to hear back from @lifupan on his analysis of why some kata-v2 tests are failing before we blindly revert this libcontainer revendoring.

**Comment by teawater** [comment]
1st test TestContainerListStatsWithIdFilter  record:
* Power8-ubuntu-16-04-PR-initrd
Not test
* opensuse-15-PR
Not test
* kata-metrics-agent-ubuntu-16-04
Not test
* kata-containers-agent-centos-7-4
Not test
* centos-7-4-PR-firecracker
Not test
* jenkins-ci-fedora
pass
* jenkins-ci-ubuntu-18-04
pass
* jenkins-ci-ubuntu-18-04-initrd
pass
* jenkins-ci-ubuntu-nemu
pass

**Comment by lifupan** [comment]
> @teawater @jodh-intel I'd like to hear back from @lifupan on his analysis of why some kata-v2 tests are failing before we blindly revert this libcontainer revendoring.

Hi @sboeuf , I'm not pretty sure that the recent CI fails on shimv2 testcase is triggered by this libcontainer vendor upgrading, but I noticed those fails appeared from that PR https://github.com/kata-containers/agent/pull/490. If we can make sure that those failures  are related with it, I think we can just revert it temporarily until we find the root cause.

**Comment by teawater** [comment]
2nd test TestContainerListStatsWithIdFilter record:
* Power8-ubuntu-16-04-PR-initrd
Not test
* opensuse-15-PR
Not test
* kata-metrics-agent-ubuntu-16-04
Not test
* kata-containers-agent-centos-7-4
Not test
* centos-7-4-PR-firecracker
Not test
* jenkins-ci-fedora
pass
* jenkins-ci-ubuntu-18-04
pass
* jenkins-ci-ubuntu-18-04-initrd
pass
* jenkins-ci-ubuntu-nemu
pass

**Comment by teawater** [comment]
3rd test TestContainerListStatsWithIdFilter record:
* Power8-ubuntu-16-04-PR-initrd
Not test
* opensuse-15-PR
Not test
* kata-metrics-agent-ubuntu-16-04
Not test
* kata-containers-agent-centos-7-4
Not test
* centos-7-4-PR-firecracker
Not test
* jenkins-ci-fedora
pass
* jenkins-ci-ubuntu-18-04
pass
* jenkins-ci-ubuntu-18-04-initrd
pass
* jenkins-ci-ubuntu-nemu
pass

**Comment by teawater** [comment]
According to the test record, I think this PR handles the issue.

**Comment by sboeuf** [comment]
@teawater @lifupan 
We know this `libcontainer` vendoring is the problem, but reverting it is not really solving the problem...
For the sake of having the CI passing again, let's merge it, but @lifupan please try to find out what is going wrong with this, as we need this revendoring to solve other issues related to `exec` cgroups and CVE.

**Comment by lifupan** [comment]
> @teawater @lifupan
> We know this `libcontainer` vendoring is the problem, but reverting it is not really solving the problem...
> For the sake of having the CI passing again, let's merge it, but @lifupan please try to find out what is going wrong with this, as we need this revendoring to solve other issues related to `exec` cgroups and CVE.

@sboeuf 
I'll have a look on this issue.

**Comment by sboeuf** [comment]
Thanks @lifupan

**Pull request merged**
