### PR TITLE
protocol: grpc: Allow several updates of the same interface

### PR DESCRIPTION
**Pull request by sboeuf**
protocol: grpc: Allow several updates of the same interface
    
    When using UpdateInterface(), the way the UpdateType is defined only
    allows for one operation at a time. This commit modifies the enum
    values of the UpdateType so that they can be used as flags. This way,
    we can combine several updates (IPs, Name, MTU) of the same interface
    in one call.
    
    Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
cc @sameo @laijs according to what we have discussed.

**Comment by gnawux** [comment]
Could we add and remove IP Addresses in a single call?

**Comment by sboeuf** [comment]
Well yes basically, that's why we need the agent implementation to forbid such behavior. In case the flag combination is `AddIP | RemoveIP`, we'll throw an error.

**Comment by gnawux** [comment]
LGTM

**Comment by sameo** [comment]
LGTM

**Comment by laijs** [comment]
hello #56 is a proper way to allow several updates of the same interface IMO.
And it also support removing&adding at the same time.

**Pull request merged**
