### PR TITLE
# Kata Containers 1.7.0-alpha0

### PR DESCRIPTION
**Pull request by egernst**
- channel: Check for channel type in kernel cmdline options
- systemd-target: Add chronyd.service to kata-containers.target
- make: Install systemd targets in systemd unit dir
- Revert vendor: Update libcontainer vendoring
- network: guest network interface support NOARP
- vendor: Update libcontainer vendoring
- lint: Switch golang linter to golangci-lint
- agent: support read-only rootfs

2af3599 channel: Check for channel type in kernel cmdline options
39696c0 vendor: Revert "vendor: Update libcontainer vendoring"
7866668 agent: Revert "agent: Fix container creation"
8f893b9 test: Revert "test: Fix mockContainer"
49e5847 systemd-target: Add chronyd.service to kata-containers.target
3aa90d2 network: guest network interface support NOARP
0bf9d1e make: Install systemd targets in systemd unit dir
7278038 lint: fix linter errors from new golang linter
b67fcc8 agent: support read-only rootfs
ab489ae test: Fix mockContainer
eb4eb55 agent: Fix container creation
a3277aa vendor: Update libcontainer vendoring

### CODE REVIEW

**Comment by devimc** [comment]
note: libcontainer was not updated

**Comment by egernst** [comment]
@devimc yeah -- saw the addition and removal.  any concern here?

**Comment by jcvenegas** [comment]
fedora: this looks interesting seems that our CI is running out of storage
```
google/protobuf/io/zero_copy_stream_impl.h google/protobuf/io/zero_copy_stream_impl_lite.h '/usr/local/include/google/protobuf/io'
 /usr/bin/mkdir -p '/usr/local/include/google/protobuf/compiler/csharp'
 /usr/bin/install -c -m 644  google/protobuf/compiler/csharp/csharp_generator.h google/protobuf/compiler/csharp/csharp_names.h '/usr/local/include/google/protobuf/compiler/csharp'
 /usr/bin/mkdir -p '/usr/local/include/google/protobuf/compiler/objectivec'
 /usr/bin/install -c -m 644  google/protobuf/compiler/objectivec/objectivec_generator.h google/protobuf/compiler/objectivec/objectivec_helpers.h '/usr/local/include/google/protobuf/compiler/objectivec'
make[3]: Leaving directory `/opt/protobuf-3.5.0/src'
make[2]: Leaving directory `/opt/protobuf-3.5.0/src'
make[1]: Leaving directory `/opt/protobuf-3.5.0/src'
Error processing tar file(exit status 1): write /opt/protobuf-3.5.0/src/google/protobuf/io/printer.o: no space left on device
```

**Pull request merged**
