### PR TITLE
logging: Redirect yamux warnings/errors to logger

### LINKED ISSUE #288: Enable yamux logging
By default yamux logs warnings and error to `stderr`. However, these messages should be redirected to the logger.

### PR DESCRIPTION
**Pull request by jodh-intel**
Capture yamux messages to the logger.

Fixes #288.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
/cc @grahamwhaley.

Related: https://github.com/kata-containers/proxy/pull/89.

**Comment by grahamwhaley** [comment]
lgtm, but I presume it might hit the same issue as the proxy equiv.
I've nudged the CI rebuild, as it felt like a net error.

**Comment by jodh-intel** [comment]
The proxy issue was caused by a bad test which was leaking resources. These tests pass for me so let's see what restarting the failing CI jobs does...

**Comment by devimc** [comment]
lgtm

I guess CI is failing because of 9p patch was not applied

**Comment by bergwolf** [comment]
LGTM! CI is still failing though...

> I guess CI is failing because of 9p patch was not applied

@devimc Are we not using prebuilt kata guest kernel binaries?

**Comment by devimc** [comment]
@bergwolf we are, but seem like the patch was not applied in obs

**Pull request merged**
