### PR TITLE
Add version option

### PR DESCRIPTION
**Pull request by jodh-intel**

### CODE REVIEW

**Comment by jodh-intel** [comment]
I'm not sure who setup the travis integration, but it's failing becase we don't have a `.travis.yml` yet, so probably best to remove Travis for now (or just ignore the error :)

**Comment by bergwolf** [comment]
@jodh-intel I enabled travis ci for #48 that adds `.travis.yml`.

**Comment by bergwolf** [comment]
@jodh-intel can you please rebase so that this includes the travis config. Thanks!

**Comment by jodh-intel** [comment]
Hi @bergwolf - done.

**Pull request merged**
