### PR TITLE
Fix dep warning and prune unneeded code

### PR DESCRIPTION
**Pull request by laijs**
Fix dep warning due to "github.com/golang/protobuf" is not
direct dependencies.

And pruning is now performed automatically by dep ensure.
So update the vendor/ and prune unneeded code.

fixes: #127

### CODE REVIEW

**Comment by bergwolf** [comment]
LGTM!

**Comment by jodh-intel** [comment]
Hi @laijs - could you add that `Fixes #127` to one of the commits to keep `checkcommits` happy?

That's an impressive reduction in code btw! ;)

**Comment by laijs** [comment]
done

**Comment by sameo** [comment]
LGTM

**Comment by jodh-intel** [comment]
lgtm

**Pull request merged**
