### PR TITLE
main: Display full stacktrace on internal error

### LINKED ISSUE #160: display full stack trace on internal error
Modify the agent to display a full stacktrace on internal error before exiting.

Note that we don't want the agent to coredump as there may be insufficient space to store it and it will be deleted on image cleanup anyway.

Related:

- https://github.com/kata-containers/proxy/issues/59
- https://github.com/kata-containers/shim/issues/57

### PR DESCRIPTION
**Pull request by jodh-intel**
Enable a full stacktrace display on internal error as an aid to
debugging.

Fixes #160.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Here's an example of what you'll find in the logs on internal error:

```
$ sudo journalctl -q -o cat -a -t kata-proxy > proxy.log && kata-log-parser --output-format json proxy.log| jq -S '.Entries[].Msg'|awk '/ABRT/{flag=1;print;next}/Stopped/{flag=0}flag'
"SIGABRT: abort\n"                                                                                                                                                                            
"PC=0x48198f m=0 sigcode=0\n"
"\n"
"goroutine 1 [running]:\n"
"syscall.RawSyscall(0x3e, 0x0, 0x6, 0x0, 0xb04cc3, 0x7, 0xb15689)\n"
"\t/usr/local/go/go1.9/go/src/syscall/asm_linux_amd64.s:78 +0x1f fp=0xc42004fe58 sp=0xc42004fe50 pc=0x48198f\n"
"syscall.Kill(0x0, 0x6, 0x7, 0xc420073800)\n"
"\t/usr/local/go/go1.9/go/src/syscall/zsyscall_linux_amd64.go:621 +0x4b fp=0xc42004fea8 sp=0xc42004fe58 pc=0x47eabb\n"
"main.main()\n"
"\t/home/james/go/src/github.com/kata-containers/agent/agent.go:466 +0xac fp=0xc42004ff80 sp=0xc42004fea8 pc=0x98a75c\n"
"runtime.main()\n"
"\t/usr/local/go/go1.9/go/src/runtime/proc.go:185 +0x20d fp=0xc42004ffe0 sp=0xc42004ff80 pc=0x42ea5d\n"
"runtime.goexit()\n"
"\t/usr/local/go/go1.9/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42004ffe8 sp=0xc42004ffe0 pc=0x45bb41\n"
"\n"
"goroutine 2 [force gc (idle)]:\n"
"runtime.gopark(0xb2f418, 0x10cc1b0, 0xb09d5a, 0xf, 0x14, 0x1)\n"
"\t/usr/local/go/go1.9/go/src/runtime/proc.go:277 +0x12c fp=0xc420024768 sp=0xc420024738 pc=0x42eefc\n"
"runtime.goparkunlock(0x10cc1b0, 0xb09d5a, 0xf, 0xc420000114, 0x1)\n"
"\t/usr/local/go/go1.9/go/src/runtime/proc.go:283 +0x5e fp=0xc4200247a8 sp=0xc420024768 pc=0x42efee\n"
"runtime.forcegchelper()\n"
"\t/usr/local/go/go1.9/go/src/runtime/proc.go:235 +0xcc fp=0xc4200247e0 sp=0xc4200247a8 pc=0x42ed1c\n"
"runtime.goexit()\n"
"\t/usr/local/go/go1.9/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc4200247e8 sp=0xc4200247e0 pc=0x45bb41\n"
"created by runtime.init.4\n"
"\t/usr/local/go/go1.9/go/src/runtime/proc.go:224 +0x35\n"
"\n"
"goroutine 3 [GC sweep wait]:\n"
"runtime.gopark(0xb2f418, 0x10cc320, 0xb08652, 0xd, 0x421c14, 0x1)\n"
"\t/usr/local/go/go1.9/go/src/runtime/proc.go:277 +0x12c fp=0xc420024f60 sp=0xc420024f30 pc=0x42eefc\n"
"runtime.goparkunlock(0x10cc320, 0xb08652, 0xd, 0x14, 0x1)\n"
"\t/usr/local/go/go1.9/go/src/runtime/proc.go:283 +0x5e fp=0xc420024fa0 sp=0xc420024f60 pc=0x42efee\n"
"runtime.bgsweep(0xc420060000)\n"
"\t/usr/local/go/go1.9/go/src/runtime/mgcsweep.go:52 +0xa3 fp=0xc420024fd8 sp=0xc420024fa0 pc=0x421cf3\n"
"runtime.goexit()\n"
"\t/usr/local/go/go1.9/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420024fe0 sp=0xc420024fd8 pc=0x45bb41\n"
"created by runtime.gcenable\n"
"\t/usr/local/go/go1.9/go/src/runtime/mgc.go:216 +0x58\n"
"\n"
"goroutine 4 [finalizer wait]:\n"
"runtime.gopark(0xb2f418, 0x10ec600, 0xb093d7, 0xe, 0x14, 0x1)\n"
"\t/usr/local/go/go1.9/go/src/runtime/proc.go:277 +0x12c fp=0xc420025700 sp=0xc4200256d0 pc=0x42eefc\n"
"runtime.goparkunlock(0x10ec600, 0xb093d7, 0xe, 0x14, 0x1)\n"
"\t/usr/local/go/go1.9/go/src/runtime/proc.go:283 +0x5e fp=0xc420025740 sp=0xc420025700 pc=0x42efee\n"
"runtime.runfinq()\n"
"\t/usr/local/go/go1.9/go/src/runtime/mfinal.go:175 +0xb8 fp=0xc4200257e0 sp=0xc420025740 pc=0x418ae8\n"
"runtime.goexit()\n"
"\t/usr/local/go/go1.9/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc4200257e8 sp=0xc4200257e0 pc=0x45bb41\n"
"created by runtime.createfing\n"
"\t/usr/local/go/go1.9/go/src/runtime/mfinal.go:156 +0x62\n"
"\n"                                                                                                                                                                                          
"goroutine 5 [syscall]:\n"                                                                                                                                                                    
"runtime.notetsleepg(0x10eca80, 0xffffffffffffffff, 0x0)\n"                                                                                                                                   
"\t/usr/local/go/go1.9/go/src/runtime/lock_futex.go:227 +0x42 fp=0xc420025f80 sp=0xc420025f50 pc=0x412782\n"                                                                                  
"os/signal.signal_recv(0x0)\n"                                                                                                                                                                
"\t/usr/local/go/go1.9/go/src/runtime/sigqueue.go:131 +0xa6 fp=0xc420025fa8 sp=0xc420025f80 pc=0x444426\n"                                                                                    
"os/signal.loop()\n"                                                                                                                                                                          
"\t/usr/local/go/go1.9/go/src/os/signal/signal_unix.go:22 +0x22 fp=0xc420025fe0 sp=0xc420025fa8 pc=0x549bc2\n"                                                                                
"runtime.goexit()\n"                                                                                                                                                                          
"\t/usr/local/go/go1.9/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420025fe8 sp=0xc420025fe0 pc=0x45bb41\n"                                                                                    
"created by os/signal.init.0\n"                                                                                                                                                               
"\t/usr/local/go/go1.9/go/src/os/signal/signal_unix.go:28 +0x41\n"                                                                                                                            
"\n"                                                                                                                                                                                          
"rax    0x0\n"                                                                                                                                                                                
"rbx    0xc420163530\n"                                                                                                                                                                       
"rcx    0x48198f\n"                                                                                                                                                                           
"rdx    0x0\n"                                                                                                                                                                                
"rdi    0x0\n"                                                                                                                                                                                
"rsi    0x6\n"                                                                                                                                                                                
"rbp    0xc42004fe98\n"                                                                                                                                                                       
"rsp    0xc42004fe50\n"                                                                                                                                                                       
"r8     0x0\n"                                                                                                                                                                                
"r9     0x0\n"                                                                                                                                                                                
"r10    0x0\n"                                                                                                                                                                                
"r11    0x246\n"                                                                                                                                                                              
"r12    0xc420172a90\n"                                                                                                                                                                       
"r13    0x1\n"                                                                                                                                                                                
"r14    0xff\n"                                                                                                                                                                               
"r15    0xc\n"                                                                                                                                                                                
"rip    0x48198f\n"                                                                                                                                                                           
"rflags 0x246\n"                                                                                                                                                                              
"cs     0x33\n"                                                                                                                                                                               
"fs     0x0\n"                                                                                                                                                                                
"gs     0x0\n"
```

**Comment by bergwolf** [comment]
lgtm

**Comment by jodh-intel** [comment]
CI failing due to https://github.com/clearcontainers/runtime/pull/1044.

**Comment by sboeuf** [comment]
LGTM

**Pull request merged**
