### PR TITLE
block: add support of block storage driver "nvdimm"

### PR DESCRIPTION
**Pull request by teawater**
Support the block storage driver "nvdimm".

Signed-off-by: Hui Zhu <teawater@hyper.sh>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Hi @teawater - Travis is failing so please could you add a "Fixes #XXX" to the commit. Also it would be useful if you could add some explanation of this feature to the commit (and ideally a unit test ;)

**Comment by teawater** [comment]
In jenkins-metrics-ubuntu-16-04:
The fail is:
10:46:24 time="2018-12-06T02:46:24Z" level=warning msg="Failed Maxval (3.045000 < 3.145800) for [boot-times]"
10:46:24 time="2018-12-06T02:46:24Z" level=warning msg="Check for [boot-times] failed [Failed]"
10:46:24 time="2018-12-06T02:46:24Z" level=warning msg=" with [[*F* boot-times 95.0% 108.5% 105.0% 10.0% 103.8% 130.0% 25.3% 4.7% 20]]"
10:46:24 time="2018-12-06T02:46:24Z" level=warning msg="Failed Minval (137263.525000 > 136598.460000) for [memory-footprint]"
10:46:24 time="2018-12-06T02:46:24Z" level=warning msg="Check for [memory-footprint] failed [Failed]"
10:46:24 time="2018-12-06T02:46:24Z" level=warning msg=" with [[*F* memory-footprint 85.0% 84.6% 115.0% 30.0% 84.6% 84.6% 0.0% 0.0% 1]]"
10:46:24 time="2018-12-06T02:46:24Z" level=warning msg="Overall we failed"
10:46:24 
10:46:24 Report Summary:
10:46:24 +-----+----------------------+-------+--------+--------+-------+--------+--------+-------+------+-----+
10:46:24 | P/F |         NAME         |  FLR  |  MEAN  |  CEIL  |  GAP  |  MIN   |  MAX   |  RNG  | COV  | ITS |
10:46:24 +-----+----------------------+-------+--------+--------+-------+--------+--------+-------+------+-----+
10:46:24 | *F* | boot-times           | 95.0% | 108.5% | 105.0% | 10.0% | 103.8% | 130.0% | 25.3% | 4.7% |  20 |
10:46:24 | *F* | memory-footprint     | 85.0% | 84.6%  | 115.0% | 30.0% | 84.6%  | 84.6%  | 0.0%  | 0.0% |   1 |
10:46:24 | P   | memory-footprint-ksm | 95.0% | 101.1% | 105.0% | 10.0% | 101.1% | 101.1% | 0.0%  | 0.0% |   1 |
10:46:24 +-----+----------------------+-------+--------+--------+-------+--------+--------+-------+------+-----+
10:46:24 Fails: 2, Passes 1
10:46:24 Failed
10:46:24 checkmetrics FAILED (1)

**Comment by bergwolf** [comment]
metrics has been failing for many PRs recently. @grahamwhaley any ideas?

**Comment by jodh-intel** [comment]
lgtm

**Pull request merged**
