### PR TITLE
codecov: Add codecov.yml

### LINKED ISSUE #84: Add codecov.yml
Add `codecov.yml` file so that we can ignore some directories.

### PR DESCRIPTION
**Pull request by sboeuf**
codecov: Add codecov.yml

This commit introduces a codecov.yml file to be able to specify
some files/directories we don't want to cover.

Fixes #84

Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
cc @bergwolf @laijs

**Comment by bergwolf** [comment]
lgtm!

**Comment by laijs** [comment]
LGTM
But the utils.go need to be moved out from the dirs. the coverage for it is essential.

**Comment by sboeuf** [comment]
@laijs @bergwolf I have modified the `codecov.yml` file so that we ignore only the files ending with `.../*.proto`, `.../*.pb.go`, and `.../*.json`

**Pull request merged**
