### PR TITLE
# Kata Containers 1.5.2

### PR DESCRIPTION
**Pull request by bergwolf**
Version bump no changes

### CODE REVIEW

**Comment by jodh-intel** [comment]
Hi @bergwolf - this looks wrong to me as there are definitely recently agent changes not being listed here.

**Comment by bergwolf** [comment]
@jodh-intel which commit are you thinking of? Please note that it is a stable release based on top of the `stable-1.5` branch.

**Comment by jodh-intel** [comment]
@bergwolf - sorry - my mistake! You are of course correct ;)

**Pull request merged**
