### PR TITLE
github: Remove issue template and use central one

### PR DESCRIPTION
**Pull request by jodh-intel**
Remove the GitHub issue template from this repository. We already have a
central set of templates [1] that are being used so the template in this
repository is redundant.

[1] - https://github.com/kata-containers/.github/tree/master/.github/ISSUE_TEMPLATE/

Fixes: #846.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm!

**Comment by jodh-intel** [comment]
One ack is all we need here folks...

**Review by devimc — APPROVED** [review]
> :musical_note:  All you need is love, love. Love is all you need :microphone: 

:laughing: lgtm - thanks @jodh-intel

**Comment by jodh-intel** [comment]
Hahaa! ;)

**Comment by jodh-intel** [comment]
Need 1 more ack from someone in the docs group...

**Comment by mvincerx** [comment]
LGTM
ack

**Comment by jodh-intel** [comment]
We need one more doc team ack to get thls landed.

**Review by egernst — APPROVED** [review]

**Pull request merged**
