### PR TITLE
channel: Support Epoll on Arm64

### PR DESCRIPTION
**Pull request by Pennyzct**
syscall.EpollWait() gives ENOSYS: function not implemented error
(from Linux kernel), thus because epoll_wait is deprecated, and
only the newer epoll_pwait is provided on Linux/arm64. Golang has
fixed this issue(https://github.com/golang/go/issues/10235).
However, the implementation exits in x/sys/unix, not in the
standard Go syscall package.

Fixes: #240

Signed-off-by: Penny Zheng <penny.zheng@arm.com>
Signed-off-by: Wei Chen <wei.chen@arm.com>

### CODE REVIEW

**Comment by bergwolf** [comment]
In that case, how about just switching to epoll_pwait?

**Comment by bergwolf** [comment]
hmm, I wanted to favor the syscall package over the unix package but I guess we are bound to linux anyway. So,
LGTM! Thanks for the patch!

**Comment by Pennyzct** [comment]
Quite a few favor the `syscall` over `x/sys/unix`, however under the discussion of the implementation of deprecated syscall on Arm64 in golang community([issue 10235](https://github.com/golang/go/issues/10235)), they chose x/sys/unix over syscall. So, it's quite the only legit solution for us. thanks for understanding.😊

**Comment by jodh-intel** [comment]
Thanks @Pennyzct.

lgtm

**Pull request merged**
