### PR TITLE
vendor: Revendor netlink to fix PID 1 segfault

### LINKED ISSUE #281: Agent is segfaulting as PID 1
The agent is segfaulting:

```
time="2018-06-27T14:36:18.013124178+01:00" level=info msg="time=\"2018-06-27T13:36:17.991658216Z\" level=info msg=\"Getting interface from MAC address\" interface-name=eth0 mac-address=\"02:42:ac:11:00:02\" name=kata-agent pid=1 source=agent\n" name=kata-proxy pid=5248 source=agent
time="2018-06-27T14:36:18.014385329+01:00" level=info msg="[    0.599563] init[66]: segfault at 0 ip 0000000000947d7a sp 000000c4201629a8 error 4 in init[400000+ad8000]\n" name=kata-proxy pid=5248 source=agent
time="2018-06-27T14:36:18.015272343+01:00" level=info msg="time=\"2018-06-27T13:36:17.993815532Z\" level=info msg=\"Link found\" interface-name=eth0 link=\"&{LinkAttrs:{Index:2 MTU:1500 TxQLen:1000 Name:eth0 HardwareAddr:02:42:ac:11:00:02 Flags:broadcast|multicast RawFlags:4098 ParentIndex:0 MasterIndex:0 Namespace:<nil> Alias: Statistics:0xc4201da5d4 Promisc:0 Xdp:0xc42006d800 EncapType:ether Protinfo:<nil> OperState:down NetNsID:0 NumTxQueues:0 NumRxQueues:0}}\" mac-address=\"02:42:ac:11:00:02\" name=kata-agent pid=1 source=agent\n" name=kata-proxy pid=5248 source=agent
```

I thought I'd fixed this on #266 and I added a CI test to fail if it found segfaults:

- https://github.com/kata-containers/tests/pull/400

### LINKED ISSUE #354: agent: get content of a file in sandbox
# Description of problem

In https://github.com/kata-containers/runtime/pull/624, we have such problems:
1. Hot add memory should be aligned to memory section size, but the size of a memory section is architecture dependent. For example, power uses 16MB, ia64 uses 1GB, x86_64 uses 128MB, ppc64le uses 256MB.
2. Each memory block is described under /sys/devices/system/memory as /sys/devices/system/memory/memoryXXX (XXX is the memory block id.), which is the unit of memory online/offline. In sparse memory model, memory block size is a multiple of memory section size, [reference](http://www.infradead.org/~mchehab/kernel_docs/unsorted/memory-hotplug.html#unit-of-memory-online-offline-operation). We can online a memory block only if we hotplug a memory-block-sized dimm, see `pages_correctly_reserved` in [reference](https://elixir.bootlin.com/linux/v4.14.49/source/drivers/base/memory.c#L230).

So we should get the size of guestos memory block by reading /sys/devices/system/memoryblock_size_bytes in sandbox, and make hot add memory to be aligned to memory block size of sandbox. 

I think it's needed to add a ReadSandboxFile rpc to read file above in a common way.

### PR DESCRIPTION
**Pull request by jodh-intel**
Update the `netlink` package to fix the segfault caused by a missing
`nil` check in the `netlink` library when running with the agent as PID 1.

The package has been updated to the latest but the crucial commit is:

    d77c86a protinfo: Check if object is nil

This also necessitated updating the `sys` package which `netlink` depends on.

`netlink` changes:

    2cbcf73 Add a test for Vlan filtering support for bridges.
    0bbc55b Initial support for vlan aware bridges.
    3ac69fd Add network namespace ID management.
    d68dce4 Ingress qdisc add/del Test case
    1006cf4 Implementation of HFSC
    d85e18e Allow Tuntap non-persist, allow empty tuntap name
    d77c86a protinfo: Check if object is nil
    a06dabf Increase size of receive buffer
    3e48e44 Revert "RTEXT_FILTER_VF doesn't always work with dump request, fixes #354"
    028453c RTEXT_FILTER_VF doesn't always work with dump request, fixes #354
    ee06b1d add vti6 support
    b1cc70d fix prefixlen/local IP, incl. PtP addresses
    7c0b594 Implemented String() for netem, fq and fq_codel in qdisc
    769bb84 Adjust flags values
    5f662e0 Add info about VFs on link
    985ab95 Add support for link flag allmulticast
    16769db Support LWTUNNEL_ENCAP_SEG6_LOCAL (including tests)
    b7f0669 Add test to Add/Del IPv6 route.
    55d3a80 Added tests for Gretap/Gretun devices
    f07d9d5 Run both Inline/Encap mode in TestSEG6RouteAddDel
    1970aef Add RDMA netlink socket for RDMA device information
    dc00cf9 Add Hash to U32
    23a36f2 Add Divisor to U32
    85aa3b7 Add statistics to class attributes
    aa0edbe Add support for setting InfininBand Node and Port GUID of a VF
    41009d5 Read conntrack flow statistics
    a2ad57a Add changelog file, initial release tagging
    5236321 Use IFLA_* constants from x/sys/unix
    25d2c79 Use IFF_MULTI_QUEUE from x/sys/unix to define TUNTAP_MULTI_QUEUE
    d35d6b5 Clarify ESN bitmap length construction logic
    a2af46a Add FQ Codel
    465b5fe Add Fq Qdisc support
    c27b7f7 Run gofmt -s -w on the project
    5f5d5cd Add a 'ListExisting' option to get the existing entries in the route/addr/link tables as part of RouteSubscribeWithOptions, AddrSubscribeWithOptions, and LinkSubscribeWithOptions.
    5a988e8 Support IPv6 GRE Tun and Tap
    7291c36 addr_linux: Implement CacheInfo installation
    422ffe6 addr_linux: Skip BROADCAST and LABEL for non-ipv4
    1882fa9 Add Matchall filter
    7b4c063 Update bpf_linux.go
    ad19ca1 netlink: allow non linux builds to pass.
    3ff4c21 Don't overwrite the XDP file descriptor with flags
    d4235bf Eliminate cgo from netlink.
    54ad9e3 Two new functions: LinkSetBondSlave and VethPeerIndex

`sys` changes:

    ac767d6 windows/svc/mgr: add ability to set a reboot message and command when a service fails
    1b2967e unix: implement RFCOMM sockets on Linux
    7b495ad unix: update Dockerfile to Go 1.11beta1
    3c6ecd8 windows: add missing file attributes
    ce36f38 unix: regenerate syscall wrappers for linux/ppc64{,le}
    151529c windows, windows/svc/mgr: add ability to modify service recovery settings.
    7138fd3 unix: do not return non-nil error for 0 errno in FcntlInt
    c4afb3e unix: fix TestUtimesNanoAt for filesystems with 1-second resolution time stamps
    a200a19 unix: don't check atime in TestUtimesNanoAt
    63fc586 unix: use private copy of ustat_t on Linux
    ad87a3a unix: check faccessat flags parameter on Linux
    fc8bd94 unix: don't use deprecated syscalls on linux/arm64
    f24d3d4 unix: add Faccessat on Solaris
    6c888cc windows: replace uintptr in crypto structs
    8014b7b windows: follow convention for generated code comment
    8883426 plan9: follow convention for generated code comment
    9e6071e unix: follow convention for generated code comment
    56ede36 unix: add rtc defines and types
    8ee9f3e unix: add Faccessat on NetBSD
    f4b713d unix: add Faccessat on OpenBSD
    a9e25c0 unix: update Dockerfile to Ubuntu 18.04, Linux 4.17, and Go 1.10.3
    bff228c windows: update TOKEN_ALL_ACCESS according to WinNT.h
    24c297a unix: support compiling with gccgo on linux/386
    7c1e4f3 unix: drop use function stub for gccgo
    9527bec cpu: fix gccgo build
    bc2ef10 cpu: add gccgo implementation
    538ab54 cpu: introduce and export type CacheLinePad
    c11f84a unix: don't check atime in TestStatx
    d4cedef unix: make Nfgenmsg a type definition
    3135538 unix: add nftables defines and types
    b269ba2 unix: fix TestXattr on android
    04b8398 unix: fix or skip failing tests on android and iOS
    e2c7578 unix: delete TestDevices for *BSD and Darwin
    56ad15c windows: add QueryServiceStatusEx function
    77b0e43 unix: add symlink-safe *xattr functions on darwin
    f3b0f5f unix: skip TestStatx if the operation is not permitted
    028bb33 unix: delete TestDevices test for Solaris
    88eb85a unix: add tests for *xattr functions
    dc67e5b windows: address error reported by vet
    0b6bef9 unix: add {get,set,remove,list}xattr on darwin
    7f59abf unix: update openbsd/amd64 to OpenBSD 6.3
    89da893 unix: exclude AUDIT_RECORD_MAGIC constant on darwin
    7c87d13 unix: add tpacket types and constants on Linux
    d0faeb5 unix: fix TestSCMCredentials to not fail when root
    9950ad1 unix: add statfs and filesystem magic constants on Linux
    7dfd129 windows: address vet reports
    64746a4 unix: address vet's finding of  wrong argument size
    7db1c3b cpu: use t.Fatal instead of t.Fatalf
    6f686a3 unix: add ErrnoName and SignalName
    78d5f26 windows/svc: correct MOVL instruction in sys_amd64.s
    4adea00 cpu: new package
    f67ecc1 unix: use Fstatat for Stat on linux/amd64
    cbbc999 unix: use pselect on amd64 to satisfy Android
    bb9c189 unix: 32-bit MIPS splice system call returns int, not int64
    79b0c68 unix: add Linux block device ioctl types and constants
    a2a4594 unix: avoid extra syscall on send/recvmsg on Linux
    3ccc7e5 unix: fix typos in linux/types.go.
    9b00609 unix: add tcp_md5sig on Linux
    b126b21 unix: re-export Fsid and Sigset_t Val member on Linux
    ecfd8b5 unix: implement getrtable/setrtable syscalls on OpenBSD
    2f57af4 unix: add wrapper around perf_event_open on Linux
    2281fa9 unix: don't export any padding/alignment fields on all platforms
    f6f3529 unix: add a step to mkall.go that generates ABI headers to be referenced from types.go
    3b87a42 unix: update Dockerfile to Linux 4.16 and Go 1.10.1
    1d206c9 unix: add FcntlInt
    fcb792c unix: unify Getsockopt*
    f67933e unix: solicit EPERM via wrong PID in creds test.
    378d26f unix: add CRTSCTS on netbsd and openbsd
    2de2067 unix: add sendfile support on Solaris
    13d03a9 unix: add GetsockoptLinger and GetsockoptTimeval
    91ee8cd unix: use strings.IndexByte instead of for loops
    1e3c777 unix: don't export padding fields on Darwin
    c488ab1 unix: add Fadvise on linux/{arm64,mipsx.mips64x,ppx64x,sparc64}
    ee8db00 unix: add Fadvise on NetBSD
    bb729a5 unix: fix TestFchmodat on Illumos
    6416052 unix: enable TestFchmodat for all Unices
    dd203b8 unix: add Fchmodat on NetBSD
    7ceb54c unix: add Fchmodat on DragonflyBSD
    f8f1a95 unix: add Fchmodat on OpenBSD
    d8e400b unix: fix example
    01acb38 plan9, unix, windows: add paragraph breaks in docs
    0deb464 unix: add Exec call
    2f1e207 unix: add IFLA attributes on linux/sparc64
    cc7307a unix: add Fstatat on Darwin
    5c2edb5 unix: add Fstatat on OpenBSD
    89ac7f2 CONTRIBUTING.md: remove note about not accepting Pull Requests
    932fb22 unix: add Fstatat on NetBSD
    2477406 unix: add Fstatat on FreeBSD
    bcaab34 unix: don't export padding fields on DragonflyBSD
    0edb963 unix: add Fstatat on DragonflyBSD
    6035cb0 unix: don't export padding fields on Solaris
    591c159 unix: add Fstatat on Solaris
    8c0ece6 unix: extend rlimit test on Linux
    c28acc8 unix: fix seek while compiling with gccgo under arm and 386
    7dca6fe plan9: use bytes.IndexByte instead of a for loop
    e64a828 unix: use bytes.IndexByte instead of a for loop
    349b81f unix: skip SchedAffinity test on single CPU system
    dd2ff4a unix: fix nil pointer dereference in Select on linux/{arm64,mips64x}
    f6cff07 windows/registry: improve ReadSubKeyNames permissions
    88d2dcc unix: add IFLA_* constants for Linux 4.15
    c1138c8 unix: update to Linux 4.15, glibc 2.27 and Go 1.10
    37707fd unix: move gccgo redeclared *SyscallNoError functions to a separate file
    8f27ce8 unix: fix cpuset size argument in sched_affinity syscall
    3dbebcf unix: use SyscallNoError and RawSyscallNoError on Linux only
    ff2a66f unix: fix godoc comment for clen
    0346725 unix: add godoc for Sockaddr* types
    90f0fdc plan9: add arm support
    ef80224 unix: add sockaddr_l2 definitions
    af9a212 unix: don't export padding fields on all platforms
    af50095 unix: use ParseDirent from syscall
    2c42eef unix: adjust replacement regex for removed struct fields for linux/s390x
    fff93fa unix: add Statx on Linux
    52ba35d unix: check error return of os.Symlink in tests on Linux
    810d700 unix: match seek argument size to signature on linux/arm
    b9cf5f9 unix: add cgroupstats type and constants
    d38bf78 unix: restore gccgo support
    2493af8 plan9: move Unsetenv into env_plan9.go
    3ca7571 windows: move Unsetenv into env_windows.go
    1792d66 unix: move Unsetenv into env_unix.go
    dd9ec17 unix: fix build on Go 1.8
    12d9d5b unix: add SchedGetaffinity and SchedSetaffinity on Linux
    a3f2cbd unix: fix typo in unix/asm_linux_arm64.s made in 28a7276
    28a7276 unix: add SyscallNoError and RawSyscallNoError on Linux
    8380141 unix: simplify error handling in *listxattr on FreeBSD
    df29b91 unix: add TestSelect for *BSD
    801364e unix: add Select on Solaris
    d818ba1 unix: remove syscall constants on Solaris
    236baca unix: add timeout tests for Select and Pselect on Linux
    571f7bb unix: simplify TestGetwd
    d5840ad unix: add GetsockoptString for Darwin, *BSD and Solaris
    1d2aa6d unix: add Getcwd to support Getwd on all BSDs
    0131e68 windows: make GetDriveType use GetDriveTypeW
    9418b3f unix: add function for converting time.Time to Timespec
    76c1389 unix: add unix.test to .gitignore
    53aa286 unix: add GetsockoptString on Linux
    b8f5ef3 unix: enable TestUname for all GOOSes
    19b530c unix: add Uname on openbsd
    a0f4589 unix: add Uname on netbsd
    9167dbf unix: add Uname on dragonfly

Fixes #281.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by bergwolf** [comment]
Nice patch! Thanks @jodh-intel !

LGTM!

**Comment by grahamwhaley** [comment]
kicked 16.04 initrd CI - curl error.

**Comment by jodh-intel** [comment]
CentOS CI:

```
Summarizing 5 Failures:

[Fail] [k8s.io] Container runtime should support basic operations on container [BeforeEach] runtime should support creating container [Conformance]                                           
/tmp/jenkins/workspace/kata-containers-agent-centos-7-4-PR/go/src/github.com/kubernetes-incubator/cri-tools/pkg/framework/util.go:152                                                         

[Fail] [k8s.io] Container runtime should support basic operations on container [BeforeEach] runtime should support starting container [Conformance]                                           
/tmp/jenkins/workspace/kata-containers-agent-centos-7-4-PR/go/src/github.com/kubernetes-incubator/cri-tools/pkg/framework/util.go:152                                                         

[Fail] [k8s.io] Container runtime should support basic operations on container [BeforeEach] runtime should support execSync [Conformance]                                                     
/tmp/jenkins/workspace/kata-containers-agent-centos-7-4-PR/go/src/github.com/kubernetes-incubator/cri-tools/pkg/framework/util.go:152                                                         

[Fail] [k8s.io] Container runtime should support basic operations on container [BeforeEach] runtime should support stopping container [Conformance]                                           
/tmp/jenkins/workspace/kata-containers-agent-centos-7-4-PR/go/src/github.com/kubernetes-incubator/cri-tools/pkg/framework/util.go:152                                                         

[Fail] [k8s.io] Container runtime should support basic operations on container [BeforeEach] runtime should support removing container [Conformance]                                           
/tmp/jenkins/workspace/kata-containers-agent-centos-7-4-PR/go/src/github.com/kubernetes-incubator/cri-tools/pkg/framework/util.go:152                                                         

Ran 5 of 71 Specs in 6.894 seconds
FAIL! -- 0 Passed | 5 Failed | 0 Pending | 66 Skipped


Ginkgo ran 1 suite in 6.953353975s
Test Suite Failed
--- FAIL: TestCRISuite (6.96s)
    cri_test.go:122: Failed to run tests in paralllel: exit status 1
FAIL
```

/me wonders if paralllel is to parallel as iff is to if? :smile:

**Comment by egernst** [comment]
hoping CRI tests on centos can get passing soon...

**Comment by sboeuf** [comment]
Just restarted the centos build as it should now be fixed by the recent PR merged from @jcvenegas

**Comment by devimc** [comment]
lgtm

**Pull request merged**
