### PR TITLE
Cpuset ignore 1.5

### PR DESCRIPTION
**Pull request by jcvenegas**
Fix for 1.5.0 branch to ignore invalid guest cpuset request.

### CODE REVIEW

**Comment by jcvenegas** [comment]
travis jobs failing, due tu missing license on pullapprove yaml, @grahamwhaley  I think we need to backport, https://github.com/kata-containers/agent/commit/00f0cf9916d86e16fce4de358ad9a3540d618e27 to all repos

**Comment by grahamwhaley** [comment]
@jcvenegas **OUCH** oh golly, that's 15 PRs per branch :-(
Maybe we can start by doing them for the repos that have PRs on... 
how about we open an Issue with a ticklist to track which ones are done already ?

**Comment by grahamwhaley** [comment]
I think the .pullapprove has been removed now. I've nudged travis for a rebuild.

**Comment by jcvenegas** [comment]
closing in this branch as it breaks some test from the stable branch will keep only on master/1.6 release

**Pull request closed without merging**
