### PR TITLE
doc: add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by caoruidong**
add a CONTRIBUTING.md for this repo

Fixes: #120

Signed-off-by: Ruidong Cao <caoruidong@huawei.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Thanks!

lgtm

**Comment by sameo** [comment]
LGTM

**Comment by sameo** [comment]
@rcaballeromx @klynnrif Could you please review this PR?

**Comment by rcaballeromx** [comment]
LGTM

**Pull request merged**
