### PR TITLE
lint: Remove unused variables and struct fields

### LINKED ISSUE #136: Remove unused variables and struct fields
The `network.dnsLock` field here is not currently used:

- https://github.com/kata-containers/agent/blob/master/network.go#L29

@sboeuf - can we remove this (atleast for the time being)? If so, we can then enable the `structcheck` gometalinter check across all the repos.

### PR DESCRIPTION
**Pull request by jodh-intel**
Remove unused variables and struct fields reported by the `structcheck`
and `unused` linters.

Fixes #136.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
@sboeuf - let's zap it for now ;)

**Comment by sboeuf** [comment]
LGTM

**Comment by sboeuf** [comment]
cc @bergwolf @laijs @WeiZhang555

**Comment by laijs** [comment]
LGTM

**Pull request merged**
