### PR TITLE
Revert: client.go: HybridVSockDialer: Change Read EOT to recv peek

### PR DESCRIPTION
**Pull request by jcvenegas**
Revert changes as bring some instability to CI. After find the root cause it will be merged again.

Fixes: #716

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Comment by jcvenegas** [comment]
Hi folks, will need to revert this changes while we  debug more kata and rust-vmm based hypervisors. Talking with @sboeuf the current code looks correct but it is making more instable the CI,  probably because it is  exposing a bad behavior in the vmm implementation, but is being hard to identify the root cause, because we dont have a CI for FC and CLH and the new rust agent is a good first step to avoid break current state the CI more.

**Comment by jcvenegas** [comment]
Here PRs using reverted changes to check CI stability. 
https://github.com/kata-containers/runtime/pull/2403
https://github.com/kata-containers/runtime/pull/2402

**Comment by likebreath** [comment]
Thanks for opening up the PR, @jcvenegas.

LGTM

**Comment by jcvenegas** [comment]
fc CI failed, expected until we revendor in runtime
```
fc6ef1ed38c0690962372cded91b63f9bb976fe357be06ffe1c6eafcdda9757a
docker: Error response from daemon: OCI runtime create failed: Failed to check if grpc server is working: context deadline exceeded: unknown.
```

**Comment by likebreath** [comment]
One minor typo in the commit message: `inestability` -> `instability`

**Pull request merged**
