### PR TITLE
vendor: update libcontainer vendoring version

### PR DESCRIPTION
**Pull request by vbmade2000**
Bump the vendoring version of libcontainer in order
to get the fix opencontainers/runc#1678 included in
our code. This will prevent libcontainer from waiting
SIGKILL'ed processes.

Fixes: #70

Signed-off-by: Malhar Vora <mlvora.2010@gmail.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Thanks very much for your contribution! There is just one last thing to do...

For re-vendor PRs like this, we list the range of commits that we're adding (in this case to `libcontainer`). That information is useful to see when looking back through the git history to help diagnose behaviour changes, etc.

For this PR, you'd do something like this:

```
$ cd $GOPATH/src/github.com/opencontainers/runc
$ old_commit=2e7cfe036e2c6dc51ccca6eb7fa3ee6b63976dcd
$ new_commit=e6516b3d5dc780cb57a976013c242a9a93052543
$ git log --no-merges --abbrev-commit --pretty=oneline "${old_commit}..${new_commit}")|sed 's/^/    /g'
```

You'd then paste the git log output into the commit body itself. The `sed` adds an indent which is useful as github then renders the commit list in a fixed-width font which looks great and makes the list easier to read. Here's an example from the Clear Containers runtime where we recently updated the virtcontainers vendoring:

- https://github.com/clearcontainers/runtime/pull/901

I've just realised that this isn't actually documented (:smile:), so I'm about to add these details to https://github.com/kata-containers/community/pull/9...

Thanks again.

**Comment by jodh-intel** [comment]
I've now updated the contributing guide PR to outline this process:

- https://github.com/kata-containers/community/pull/9

**Comment by vbmade2000** [comment]
@jodh-intel  Sure. Done.

**Comment by jodh-intel** [comment]
Thanks! I've just noticed that there are 3 commits here. I think you only need a single one and I don't think you should need a merge commit? You should be able to:

- clone https://github.com/kata-containers/agent/
- `git checkout -b ISSUE-70`
- run `go dep`
- `git commit`
- `git push -f` to your https://github.com/vbmade2000/agent branch.

**Pull request closed without merging**
