### PR TITLE
test: Increase unit test coverage

### LINKED ISSUE #86: Increase unit test coverage
The unit testing coverage should be increased with a first pass covering all the functions easily testable.

### PR DESCRIPTION
**Pull request by sboeuf**
test: Increase unit test coverage
    
    This commit adds some unit tests to cover few functions from the
    following files: agent.go, channel.go and config.go.
    
    Fixes #86
    
    Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Do those copyright headers need to specify 2018?

lgtm

**Comment by sboeuf** [comment]
Oh yes you're right, let me update them.

**Comment by jodh-intel** [comment]
lgtm

**Comment by sboeuf** [comment]
@sameo @bergwolf @laijs please check this.

**Comment by sameo** [comment]
LGTM

**Pull request merged**
