### PR TITLE
vendor: Initialize the vendoring with dep tool

### LINKED ISSUE #32: Vendor dependencies using dep tool
In order to prevent the agent from being broken every time some dependencies are going to change, we need to vendor them. The tool we chose for that is `dep` from https://github.com/golang/dep.

### PR DESCRIPTION
**Pull request by sboeuf**
vendor: Initialize the vendoring with dep tool
    
    This is the first commit related to the vendoring of all dependencies.
    This will prevent from any breakage in case a dependency would break
    the backward compatibility.
    
    Fixes #32
    
    Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
Fixes #32 
cc @sameo @WeiZhang555 @laijs @gnawux @bergwolf

**Comment by WeiZhang555** [comment]
I think we can add 
```
[prune]
  go-tests = true
```

to remove all "_test.go" test files as we don't need them for compilation.

Another option is `unused-packages = true`, but I'm not sure if it will make lots of differences.

**Comment by jodh-intel** [comment]
@WeiZhang555 - good call! `dep` seems to have grown so new features recently:

- https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md#prune

**Comment by sboeuf** [comment]
@WeiZhang555 sure, I'll update that !

**Comment by sboeuf** [comment]
@WeiZhang555 @jodh-intel I have updated the PR. However, the `_test.go` files have not been removed from `/vendor`. I am wondering if this new feature is stable yet.

**Comment by jodh-intel** [comment]
Well, the code to prune the test files looks pretty simple:

- https://github.com/golang/dep/blob/master/gps/prune.go#L279..L317

**Comment by bergwolf** [comment]
fyi, I submitted #48 to enable travis and noticed that there is no vendor in agent. So I took the liberty to add vendor support there as well. I can rebase #48 if this PR got merged first.

**Comment by bergwolf** [comment]
The prune options in `Gopkg.toml` are used to control `dep ensure` behavior and they are not implemented yet. See https://github.com/golang/dep/issues/944

**Comment by WeiZhang555** [comment]
Maybe we can merge this first, in case it blocks others. 

LGTM

**Comment by laijs** [comment]
It is cherry-picked in #48 , thank you! @sboeuf @bergwolf

**Pull request closed without merging**
