### PR TITLE
fix uevent related errors

### PR DESCRIPTION
**Pull request by bergwolf**
When testing network hotplug, I see some uevent listener related errors:
1. panic on closing the notification channels
2. device might appear before we listen to the uevents
3. panic on returning negative count in Read method to bufio

Note that even with this PR, network hotplug is still not working for me.

/cc @devimc @caoruidong @sboeuf

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm

We really need tests for that package... I've raised #368 if anyone feels like working on that? :)

**Comment by egernst** [comment]
@bergwolf should we consider this for stable?

**Comment by caoruidong** [comment]
lgtm

**Comment by bergwolf** [comment]
@egernst Yes, I think so. I didn't find the stable tag though. How do you want to tag it?

**Comment by sboeuf** [comment]
Travis stuck again, ignoring and merging.

**Pull request merged**
