### PR TITLE
fix typo in grpc.go

### LINKED ISSUE #832: Found  typo in grpc.go
cpusetGuest should be newCpuset in log

### PR DESCRIPTION
**Pull request by choury**
fix #832 
cpusetGuest should be newCpuset in log

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm!

**Comment by fidencio** [comment]
The patch itself look good. However, you're missing the `Signed-off-by: ...`.
Please, check: https://github.com/kata-containers/agent/pull/831/checks?check_run_id=1054184670

**Comment by fidencio** [comment]
@choury, now the travis-ci is failing because you have to open an issue, and link this issue to the commit you're pushing, using: "Fixes: #NNN".

Once it's done, we can run the CI against the patch.

**Review by bpradipt — COMMENTED** [review]
/lgtm

**Comment by bpradipt** [comment]
@choury the commit message needs a subsystem, otherwise Travis will complain. 
Please change the commit message to "grpc: cpusetGuest should be newCpuset in log"

**Review by bpradipt — APPROVED** [review]
@choury once you fix the commit message CI will be happy and we can merge this
Thanks

**Comment by fidencio** [comment]
* jenkins-ci-rhel-8-q35:
```
Fedora Modular 30 - x86_64                      0.0  B/s |   0  B     01:00    
Errors during downloading metadata for repository 'fedora-modular':
  - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-30&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
Error: Failed to download metadata for repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-30&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
The command '/bin/sh -c dnf -y update && dnf install -y     autoconf     automake     binutils     chrony     cmake     coreutils     curl     curl     gcc     gcc-c++     git     glibc-common     glibc-devel     glibc-headers     glibc-static     glibc-utils     libseccomp     libseccomp-devel     libstdc++-devel     libstdc++-static     m4     make     pkgconfig     sed     systemd     tar     vim     which' returned a non-zero code: 1
Failed at 125: sudo -E AGENT_INIT="${AGENT_INIT}" AGENT_VERSION="${agent_commit}" GOPATH="$GOPATH" USE_DOCKER=true OS_VERSION=${os_version} ./rootfs-builder/rootfs.sh "${distro}"
Failed at 27: "${cidir}/install_kata_image.sh" "${tag}"
Build step 'Execute shell' marked build as failure
```
Retriggering should help.  In any case, we should use a newer version of the Fedora container for this.

**Pull request merged**
