### PR TITLE
README: Test PR for CI [WIP]

### PR DESCRIPTION
**Pull request by nitkon**
This is a test PR to see how
CI on Power8 machine is running.

### CODE REVIEW

**Comment by nitkon** [comment]
All tests passed but CI failed due to leaky pods issue. The journalctl logs are here:https://github.com/kata-containers/runtime/pull/1267#issuecomment-468313710

**Comment by nitkon** [comment]
For the record: 
power-CI

**Comment by egernst** [comment]
this still needed?  If not, can you please close @nitkon?

**Pull request closed without merging**
