### PR TITLE
[RFC] Initial gRPC protocol for agent communication

### PR DESCRIPTION
**Pull request by gnawux**
based on hyperstart gRPC protocol and the discussion in hyperhq/runv#628 and
kata-containers/runtimes#2

### CODE REVIEW

**Comment by sameo** [comment]
My only concern is the `StringUser` part. I believe it's not needed, so I'll open an issue for it.
For now, this LGTM.

**Comment by sameo** [comment]
@laijs PTAL and if this looks good to you we'll merge.

**Comment by gnawux** [comment]
OK. Good start point.

I add `Hyper Inc` copyright for the files from runV originally, and add ` Intel Corporation` copyright for those comes from  hyperhq/runv#628.

However, I am thinking if we should put some header for kata org itself.

**Comment by sameo** [comment]
@gnawux Thanks for putting the right copyright, I appreciate.
I don't think we want to give code copyrights to the kata organization, but I am not a lawyer :)

**Comment by gnawux** [comment]
@sameo afaik we may have an additional header, such as

```
// Copyright 2017 HyperHQ Inc.
// Copyright 2017-2018 Kata...
```

But I don't know how it works in detail, I am not a lawyer as well.

**Comment by laijs** [comment]
LGTM

**Pull request merged**
