### PR TITLE
build: fix make proto error

### LINKED ISSUE #335: make proto fail
# Description of problem
When I  execute `make proto`, I got an error.
```
Step 7/20 : RUN curl -fkL https://storage.googleapis.com/golang/go${GO_VERSION}.linux-$(arch).tar.gz    | tar -zxC /usr/local/
 ---> Running in 4e6434b2fdc5
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
```

# Cause
In agent/Dockerfile, we can find `${GO_VERSION}` is `1.9.2`. But `$(arch)` is to execute `arch` command. On a x86_64 machine,  `$(arch)` 's result is `x86_64` in a CentOS container. So the URL will be "https://storage.googleapis.com/golang/go1.9.2.linux-x86_64.tar.gz". This is unreachable.
What we need is "https://storage.googleapis.com/golang/go1.9.2.linux-amd64.tar.gz".
The value of `arch` should be `amd64` which is getting by `go env GOARCH` and this is already pass to Dockerfile by `ARG arch`. 

# Solution
So we should change $(arch) to ${arch}

### PR DESCRIPTION
**Pull request by linzichang**
Fixes #335

Signed-off-by: Zichang Lin <linzichang@huawei.com>

### CODE REVIEW

**Comment by clarecch** [comment]
nice catch

**Comment by ydjainopensource** [comment]
A minor Patch LGTM.

**Comment by caoruidong** [comment]
LGTM

**Comment by bergwolf** [comment]
LGTM

**Comment by jodh-intel** [comment]
lgtm

**Comment by linzichang** [comment]
Yep, the CI is green now.

**Comment by jodh-intel** [comment]
Related: #340.

**Pull request merged**
