### PR TITLE
# Kata Containers this-is-a-test

### PR DESCRIPTION
**Pull request by katabuilder**
- proto: Add network stats

d9aa453 proto: add network stats

### CODE REVIEW

**Comment by grahamwhaley** [comment]
@nitkon @jcvenegas - not sure if we need to test this (and/or all its relations) do we? I think these are experimental release-bot items, and probably need closing down - @jcvenegas pls let us know.

**Comment by nitkon** [comment]
@grahamwhaley: I was just wanted to see if P8 CI runs error free on any of the PR's. So chose this test PR.

**Comment by chavafg** [comment]
is this still needed or can we close? 
@jcvenegas

**Pull request closed without merging**
