### PR TITLE
grpc: add unit test for onlineResources function

### LINKED ISSUE #387: Write unit tests for onlineResources
The `onlineResources()` function needs unit tests.

### PR DESCRIPTION
**Pull request by devimc**
Unit test for `onlineResources` function.

fixes #387

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
Travis fail:

```
/home/travis/gopath/src/github.com/kata-containers/agent/protocols/mockserver
grpc_test.go:1050:2: ineffectual assignment to `r` (ineffassign)
	r, err = onlineResources(resource, expectedCpus)
	^
The command ".ci/static-checks.sh" failed and exited with 1 during .
```

**Comment by devimc** [comment]
@grahamwhaley fixed, thanks

**Comment by amshinde** [comment]
Looks like the fedora tests are failing. I think we can ignore those right @GabyCT ?

**Comment by GabyCT** [comment]
@amshinde yes, we can ignore it, currently Fedora has issues https://github.com/kata-containers/tests/issues/1531

**Pull request merged**
