### PR TITLE
client: Dont try connect to non existing socket.

### PR DESCRIPTION
**Pull request by jcvenegas**
When a new Client is created, it tries to connect to
a socket no matter if exist or not. This is not
and issue because the grpc api will time out after
some time. But some simple task like kata-runtime list can
take a lot of the socket does not exist because the
VM and proxy top working.

Fixes: #453

### CODE REVIEW

**Comment by sboeuf** [comment]
ping @jcvenegas @bergwolf @mcastelino

**Comment by jcvenegas** [comment]
@sboeuf  so what about add and timeout option and from proxy client increase to wait for the VM socket?

**Comment by jodh-intel** [comment]
Ping @jcvenegas, @sboeuf.

**Comment by grahamwhaley** [comment]
Marking this as DNM until @jcvenegas @sboeuf re-visit and update it.

**Comment by bergwolf** [comment]
@sboeuf Yes, I share the same concern. Since we spawn the proxy process and try to connect to it without any synchronization to make sure the proxy is ready, such race can happen IMOH.

**Comment by jodh-intel** [comment]
@sboeuf, @bergwolf - It might be just me, but reading through the comments, it's not clear whether you are saying this PR is helping or not?

**Comment by jcvenegas** [comment]
@jodh-intel I talk with Sebastien offline about it, I will extend the function cal arguments l to provide a timeout, so runtime can use timeout 0 call and the proxy add  a timeout just  for the initial proxy setup.

**Comment by grahamwhaley** [comment]
@jcvenegas @sboeuf - any update on this - did you get to discuss and come to a conclusion:
- can we fix this with timeouts
- should we close this PR?

**Comment by sboeuf** [comment]
@jcvenegas did you get a chance to update the PR?

**Pull request closed without merging**
