### PR TITLE
vendor: Update vendor/github.com/opencontainers/runc

### PR DESCRIPTION
**Pull request by chavafg**
This runc revision contains fixes for:
`failed to write to cgroup.procs` when running `exec`
command.

Fixes: #476.

Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Hi @chavafg - thanks for raising!

Please could you add in the `git log` summary of changes being introduced here by running the commands here:

- https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#re-vendor-prs

From the `Gopkg.toml` file changes, these are the values you'll want before running the `git log` in that doc:

```sh
$ old_commit=cc4307ab6643668ce5abc6b524e1764a54c32550
$ new_commit=f414f497b50a61750ea3af9fccf998a3db687cea
```

**Comment by chavafg** [comment]
Seems like this is gonna need further modifications?
I am getting errors when running a container using this revendoring:
```
$ sudo docker run -ti busybox sh
docker: Error response from daemon: OCI runtime create failed: rpc error: code = Internal desc = Could not run process: container_linux.go:344: starting container process caused "exec: \"sh\": executable file not found in $PATH": unknown.
```

**Comment by jodh-intel** [comment]
Ouch. If you [enable full debug](https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#enable-full-debug), it would be interesting to see the proxy log.

**Comment by chavafg** [comment]
I think these are the relevant lines of the `kata-proxy` journal:
```
Mar 13 15:11:16 agenttest kata-proxy[17948]: time="2019-03-13T15:11:16.679045739Z" level=info msg="[    0.656318] pci 0000:00:02.0: PCI bridge to [bus 01]\n" name=kata-proxy pid=17948 sandbox=9bec385ef57293e4a3e
75364aee1f86c57e30aff42a84a218c4cc997ec07c2ae source=agent
Mar 13 15:11:16 agenttest kata-proxy[17948]: time="2019-03-13T15:11:16.67936556Z" level=info msg="[    0.656563] pci 0000:00:02.0:   bridge window [io  0xc000-0xcfff]\n" name=kata-proxy pid=17948 sandbox=9bec385
ef57293e4a3e75364aee1f86c57e30aff42a84a218c4cc997ec07c2ae source=agent
Mar 13 15:11:16 agenttest kata-proxy[17948]: time="2019-03-13T15:11:16.680889959Z" level=info msg="[    0.658042] pci 0000:00:02.0:   bridge window [mem 0xfe400000-0xfe5fffff]\n" name=kata-proxy pid=17948 sandbo
x=9bec385ef57293e4a3e75364aee1f86c57e30aff42a84a218c4cc997ec07c2ae source=agent
Mar 13 15:11:16 agenttest kata-proxy[17948]: time="2019-03-13T15:11:16.681977929Z" level=info msg="[    0.659139] pci 0000:00:02.0:   bridge window [mem 0xfe800000-0xfe9fffff 64bit pref]\n" name=kata-proxy pid=1
7948 sandbox=9bec385ef57293e4a3e75364aee1f86c57e30aff42a84a218c4cc997ec07c2ae source=agent
Mar 13 15:11:16 agenttest kata-proxy[17948]: time="2019-03-13T15:11:16.737280119Z" level=info msg="time=\"2019-03-13T15:11:16.7230686Z\" level=debug msg=\"Container doesn't exist\" container-id=9bec385ef57293e4a
3e75364aee1f86c57e30aff42a84a218c4cc997ec07c2ae name=kata-agent pid=79 sandbox=9bec385ef57293e4a3e75364aee1f86c57e30aff42a84a218c4cc997ec07c2ae source=agent\n" name=kata-proxy pid=17948 sandbox=9bec385ef57293e4a
3e75364aee1f86c57e30aff42a84a218c4cc997ec07c2ae source=agent
Mar 13 15:11:16 agenttest kata-proxy[17948]: time="2019-03-13T15:11:16.737406927Z" level=info msg="time=\"2019-03-13T15:11:16.723275058Z\" level=debug msg=\"request end\" duration=63.961808ms error=\"rpc error:
code = Internal desc = Could not run process: container_linux.go:344: starting container process caused \\\"exec: \\\\\\\"bash\\\\\\\": executable file not found in $PATH\\\"\" name=kata-agent pid=79 request=/gr
pc.AgentService/CreateContainer resp=\"&Empty{}\" sandbox=9bec385ef57293e4a3e75364aee1f86c57e30aff42a84a218c4cc997ec07c2ae source=agent\n" name=kata-proxy pid=17948 sandbox=9bec385ef57293e4a3e75364aee1f86c57e30a
ff42a84a218c4cc997ec07c2ae source=agent
Mar 13 15:11:16 agenttest kata-proxy[17948]: time="2019-03-13T15:11:16.737948763Z" level=info msg="time=\"2019-03-13T15:11:16.723503485Z\" level=info msg=\"ignoring unexpected signal\" name=kata-agent pid=79 san
dbox=9bec385ef57293e4a3e75364aee1f86c57e30aff42a84a218c4cc997ec07c2ae signal=\"child exited\" source=agent\n" name=kata-proxy pid=17948 sandbox=9bec385ef57293e4a3e75364aee1f86c57e30aff42a84a218c4cc997ec07c2ae so
urce=agent
Mar 13 15:11:16 agenttest kata-proxy[17948]: time="2019-03-13T15:11:16.740437724Z" level=info msg="time=\"2019-03-13T15:11:16.723978337Z\" level=info msg=\"ignoring unexpected signal\" name=kata-agent pid=79 san
dbox=9bec385ef57293e4a3e75364aee1f86c57e30aff42a84a218c4cc997ec07c2ae signal=\"child exited\" source=agent\n" name=kata-proxy pid=17948 sandbox=9bec385ef57293e4a3e75364aee1f86c57e30aff42a84a218c4cc997ec07c2ae so
urce=agent
Mar 13 15:11:16 agenttest kata-proxy[17948]: time="2019-03-13T15:11:16.740490228Z" level=info msg="time=\"2019-03-13T15:11:16.725379745Z\" level=info msg=\"ignoring unexpected signal\" name=kata-agent pid=79 san
dbox=9bec385ef57293e4a3e75364aee1f86c57e30aff42a84a218c4cc997ec07c2ae signal=\"child exited\" source=agent\n" name=kata-proxy pid=17948 sandbox=9bec385ef57293e4a3e75364aee1f86c57e30aff42a84a218c4cc997ec07c2ae so
urce=agent
Mar 13 15:11:16 agenttest kata-proxy[17948]: time="2019-03-13T15:11:16.801044558Z" level=info msg="time=\"2019-03-13T15:11:16.78683902Z\" level=debug msg=\"new request\" name=kata-agent pid=79 req= request=/grpc.AgentService/DestroySandbox sandbox=9bec385ef57293e4a3e75364aee1f86c57e30aff42a84a218c4cc997ec07c2ae source=agent\n" name=kata-proxy pid=17948 sandbox=9bec385ef57293e4a3e75364aee1f86c57e30aff42a84a218c4cc997ec07c2ae source=agent
Mar 13 15:11:16 agenttest kata-proxy[17948]: time="2019-03-13T15:11:16.806681324Z" level=info msg="time=\"2019-03-13T15:11:16.792465414Z\" level=debug msg=\"request end\" duration=5.404446ms name=kata-agent pid=79 request=/grpc.AgentService/DestroySandbox resp=\"&Empty{}\" sandbox=9bec385ef57293e4a3e75364aee1f86c57e30aff42a84a218c4cc997ec07c2ae source=agent\n" name=kata-proxy pid=17948 sandbox=9bec385ef57293e4a3e75364aee1f86c57e30aff42a84a218c4cc997ec07c2ae source=agent
Mar 13 15:11:16 agenttest kata-proxy[17948]: time="2019-03-13T15:11:16.807553081Z" level=fatal msg="channel error" error="accept unix /run/vc/sbs/9bec385ef57293e4a3e75364aee1f86c57e30aff42a84a218c4cc997ec07c2ae/proxy.sock: use of closed network connection" name=kata-proxy pid=17948 sandbox=9bec385ef57293e4a3e75364aee1f86c57e30aff42a84a218c4cc997ec07c2ae source=proxy
```

**Comment by jodh-intel** [comment]
@chavafg - are you sure you didn't run `sudo docker run -ti busybox bash` as that is the command that fails to be found in that log? But that's correct as the `busybox` image doesn't contain `bash` afaik.

**Comment by chavafg** [comment]
@jodh-intel pretty sure, I tried with both `ubuntu bash` and `busybox sh`

Here a log with `sh`
```
Mar 13 14:53:39 agenttest kata-proxy[13720]: time="2019-03-13T14:53:39.988993827Z" level=info msg="[    0.671408] pci 0000:00:02.0: PCI bridge to [bus 01]\n" name=kata-proxy pid=13720 sandbox=df9cbe19f4076484a5b
f72959bcfbcdb1ac0a8099239b6f77a7de8458d652f03 source=agent
Mar 13 14:53:39 agenttest kata-proxy[13720]: time="2019-03-13T14:53:39.989222839Z" level=info msg="[    0.671728] pci 0000:00:02.0:   bridge window [io  0xc000-0xcfff]\n" name=kata-proxy pid=13720 sandbox=df9cbe
19f4076484a5bf72959bcfbcdb1ac0a8099239b6f77a7de8458d652f03 source=agent
Mar 13 14:53:39 agenttest kata-proxy[13720]: time="2019-03-13T14:53:39.990662117Z" level=info msg="[    0.673176] pci 0000:00:02.0:   bridge window [mem 0xfe400000-0xfe5fffff]\n" name=kata-proxy pid=13720 sandbo
x=df9cbe19f4076484a5bf72959bcfbcdb1ac0a8099239b6f77a7de8458d652f03 source=agent
Mar 13 14:53:39 agenttest kata-proxy[13720]: time="2019-03-13T14:53:39.991769077Z" level=info msg="[    0.674247] pci 0000:00:02.0:   bridge window [mem 0xfe800000-0xfe9fffff 64bit pref]\n" name=kata-proxy pid=1
3720 sandbox=df9cbe19f4076484a5bf72959bcfbcdb1ac0a8099239b6f77a7de8458d652f03 source=agent
Mar 13 14:53:40 agenttest kata-proxy[13720]: time="2019-03-13T14:53:40.046744768Z" level=info msg="time=\"2019-03-13T14:53:40.032165888Z\" level=debug msg=\"Container doesn't exist\" container-id=df9cbe19f407648
4a5bf72959bcfbcdb1ac0a8099239b6f77a7de8458d652f03 name=kata-agent pid=82 sandbox=df9cbe19f4076484a5bf72959bcfbcdb1ac0a8099239b6f77a7de8458d652f03 source=agent\n" name=kata-proxy pid=13720 sandbox=df9cbe19f407648
4a5bf72959bcfbcdb1ac0a8099239b6f77a7de8458d652f03 source=agent
Mar 13 14:53:40 agenttest kata-proxy[13720]: time="2019-03-13T14:53:40.046896476Z" level=info msg="time=\"2019-03-13T14:53:40.032290271Z\" level=debug msg=\"request end\" duration=62.590453ms error=\"rpc error:
code = Internal desc = Could not run process: container_linux.go:344: starting container process caused \\\"exec: \\\\\\\"sh\\\\\\\": executable file not found in $PATH\\\"\" name=kata-agent pid=82 request=/grpc
.AgentService/CreateContainer resp=\"&Empty{}\" sandbox=df9cbe19f4076484a5bf72959bcfbcdb1ac0a8099239b6f77a7de8458d652f03 source=agent\n" name=kata-proxy pid=13720 sandbox=df9cbe19f4076484a5bf72959bcfbcdb1ac0a809
9239b6f77a7de8458d652f03 source=agent
Mar 13 14:53:40 agenttest kata-proxy[13720]: time="2019-03-13T14:53:40.050072449Z" level=info msg="time=\"2019-03-13T14:53:40.032646146Z\" level=info msg=\"ignoring unexpected signal\" name=kata-agent pid=82 san
dbox=df9cbe19f4076484a5bf72959bcfbcdb1ac0a8099239b6f77a7de8458d652f03 signal=\"child exited\" source=agent\n" name=kata-proxy pid=13720 sandbox=df9cbe19f4076484a5bf72959bcfbcdb1ac0a8099239b6f77a7de8458d652f03 so
urce=agent
Mar 13 14:53:40 agenttest kata-proxy[13720]: time="2019-03-13T14:53:40.050289561Z" level=info msg="time=\"2019-03-13T14:53:40.035691661Z\" level=info msg=\"ignoring unexpected signal\" name=kata-agent pid=82 san
dbox=df9cbe19f4076484a5bf72959bcfbcdb1ac0a8099239b6f77a7de8458d652f03 signal=\"child exited\" source=agent\n" name=kata-proxy pid=13720 sandbox=df9cbe19f4076484a5bf72959bcfbcdb1ac0a8099239b6f77a7de8458d652f03 so
urce=agent
Mar 13 14:53:40 agenttest kata-proxy[13720]: time="2019-03-13T14:53:40.050516873Z" level=info msg="time=\"2019-03-13T14:53:40.035884434Z\" level=info msg=\"ignoring unexpected signal\" name=kata-agent pid=82 san
dbox=df9cbe19f4076484a5bf72959bcfbcdb1ac0a8099239b6f77a7de8458d652f03 signal=\"child exited\" source=agent\n" name=kata-proxy pid=13720 sandbox=df9cbe19f4076484a5bf72959bcfbcdb1ac0a8099239b6f77a7de8458d652f03 so
urce=agent
Mar 13 14:53:40 agenttest kata-proxy[13720]: time="2019-03-13T14:53:40.128905339Z" level=info msg="time=\"2019-03-13T14:53:40.114337592Z\" level=debug msg=\"new request\" name=kata-agent pid=82 req= request=/grp
c.AgentService/DestroySandbox sandbox=df9cbe19f4076484a5bf72959bcfbcdb1ac0a8099239b6f77a7de8458d652f03 source=agent\n" name=kata-proxy pid=13720 sandbox=df9cbe19f4076484a5bf72959bcfbcdb1ac0a8099239b6f77a7de8458d
652f03 source=agent
Mar 13 14:53:40 agenttest kata-proxy[13720]: time="2019-03-13T14:53:40.134088221Z" level=info msg="time=\"2019-03-13T14:53:40.119461861Z\" level=debug msg=\"request end\" duration=4.945288ms name=kata-agent pid=
82 request=/grpc.AgentService/DestroySandbox resp=\"&Empty{}\" sandbox=df9cbe19f4076484a5bf72959bcfbcdb1ac0a8099239b6f77a7de8458d652f03 source=agent\n" name=kata-proxy pid=13720 sandbox=df9cbe19f4076484a5bf72959
bcfbcdb1ac0a8099239b6f77a7de8458d652f03 source=agent
```

**Comment by jodh-intel** [comment]
I'll tal at this tomorrow if nobody else gets around to it before then...

**Comment by chavafg** [comment]
closing in favor of #490

**Pull request closed without merging**
