### PR TITLE
proto: Split reusable structures into their own package

### LINKED ISSUE #399: protocols: grpc: Split reusable types into their own package
We need to move the Go structures that are generic enough to be reused outside the agent. This way, we don't force the consumer to pull the entire `grpc` package.

### PR DESCRIPTION
**Pull request by sboeuf**
Some structures such as Interface and Route are not only used by the
kata-agent since they are generic enough to be reused by kata-runtime
or kata-netmon.

By splitting those structures into their separate package, we prevent
their consumers from importing the whole protocols/grpc package which
pulls a lot of unneeded content.

Depends-on: github.com/kata-containers/runtime#858

Fixes #399

Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
*A la* #402, Travis doesn't like this change either :(

**Comment by sboeuf** [comment]
Depends on https://github.com/kata-containers/tests/pull/852

**Comment by sboeuf** [comment]
@amshinde @devimc @caoruidong @jodh-intel 
This PR is ready to be merged, it relies on the runtime PR https://github.com/kata-containers/runtime/pull/858 to make the CI passing.

**Comment by jodh-intel** [comment]
lgtm

**Comment by caoruidong** [comment]
This is really helpful. lgtm

**Pull request merged**
