### PR TITLE
grpc: Add health service unit tests

### PR DESCRIPTION
**Pull request by sameo**
Generated by gogoproto.

Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>

### CODE REVIEW

**Comment by sameo** [comment]
cc @WeiZhang555 @bergwolf

**Comment by bergwolf** [comment]
Thanks @sameo ! It seems there are changes introduced by "gogoproto" upgrade. Can you please split this in two commits so that one commit contains only health service unit tests related change?

**Comment by sameo** [comment]
@bergwolf, sure, done.

**Comment by WeiZhang555** [comment]
Hi @sameo , can you try to update proto with `make proto` command?  I introduced a Dockerfile for this in case different gogoproto versions make these files changed again and again.

I see some difference when I run `make proto` on your PR :smile: 

```
$ git status
On branch health-unit
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   protocols/grpc/agent.pb.go
	modified:   protocols/grpc/health.pb.go
	modified:   protocols/grpc/healthpb_test.go
	modified:   protocols/grpc/oci.pb.go
	modified:   protocols/grpc/ocipb_test.go

```

**Comment by bergwolf** [comment]
Maybe we should stick with a release of gogoproto instead of randomly downloaded ones? The latest release is https://github.com/gogo/protobuf/releases/tag/v0.5

**Comment by sameo** [comment]
Using `make proto` generates a cleaner change indeed.

**Comment by bergwolf** [comment]
LGTM

**Comment by WeiZhang555** [comment]
> Maybe we should stick with a release of gogoproto instead of randomly downloaded ones? The latest release is https://github.com/gogo/protobuf/releases/tag/v0.5

@bergwolf The Dockerfile and `make proto` is exactly for doing this. We can update the gogoproto commit in Dockerfile once we think it's necessary.

**Pull request merged**
