### PR TITLE
network: handle error case in getInterface/updateInterface

### LINKED ISSUE #151: Make getInterface return an error
This function...

```
func getInterface(netHandle *netlink.Handle, link netlink.Link) *pb.Interface
```

... needs to be changed to:

```
func getInterface(netHandle *netlink.Handle, link netlink.Link) (*pb.Interface, error)
```

since it can fail (currently the call to `netHandle.AddrList()` logs an error, but the code continues).

### PR DESCRIPTION
**Pull request by egernst**
-Handle error case and return error from the function getInterface.
-Removed goto usage and replaced with defer func() handling within
updateInterface function.
-Added comment describing the updateInterface function
-validate iface parameter before nethandle to avoid unnecessary work
if we have an error

Fixes #151

Signed-off-by: Eric Ernst <eric.ernst@intel.com>

### CODE REVIEW

**Comment by egernst** [comment]
@bergwolf @WeiZhang555 @sboeuf PTAL

**Comment by sboeuf** [comment]
LGTM

**Comment by WeiZhang555** [comment]
LGTM

**Comment by WeiZhang555** [comment]
Jenkins failed, can you push again to retrigger CI? To check if this is only an one-time failure.

**Comment by egernst** [comment]
Rebased and removed unused const (@WeiZhang555 - thanks :))

This will fail jenkins until https://github.com/kata-containers/agent/pull/153 merges.  Can someone take a look at 153 -- should be good to merge...

**Comment by egernst** [comment]
Rebased and pushed -- jenkins should be happy now!

**Comment by grahamwhaley** [comment]
Just a note/thought - if this is the Jenkins CI (I cannot see on github now it has been merged ;-) ), then you don't need to rebase/push to get a rebuild - there should be a 'rebuild' button/option on the Jenkins itself you can use ;-)

**Comment by caoruidong** [comment]
@grahamwhaley You can tap [View details] button beside [Revert] to see Jenkins detail

**Comment by grahamwhaley** [comment]
OOh, thanks @caoruidong , I'd never worked that out :-)
and, just for reference, yes, we do have the 'rebuild' plugin enabled in Jenkins :-)
http://kata-jenkins-ci.westus2.cloudapp.azure.com/job/kata-containers-agent-ubuntu-16-04-PR/6/rebuild

**Pull request merged**
