### PR TITLE
vendor: update gogo/protobuf to v1.2.1

### PR DESCRIPTION
**Pull request by lifupan**
Since runtime needs to update gogo/protobuf to v1.2.1
to support latest shimv2, in order to keep align with
runtime, update it too.

Fixes:#555

Signed-off-by: lifupan <lifupan@gmail.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Hi @lifupan - please can you paste the output of the `git log` command in the doc below into the commit so we can see exactly what changed:

- https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#re-vendor-prs

**Comment by lifupan** [comment]
> Hi @lifupan - please can you paste the output of the `git log` command in the doc below into the commit so we can see exactly what changed:
> 
> * https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#re-vendor-prs

Hi @jodh-intel  Updated.

**Comment by jodh-intel** [comment]
Another dead sles CI link I think @chavafg.

Merging...

**Pull request merged**
